import { createPatient } from './Patient.js';

export const mockPatients = [
  createPatient({
    id: 'p1',
    name: 'Mary Doherty',
    dob: '14/03/1959',
    age: 67,
    sex: 'Female',
    mrn: 'MRN-0042851',
    gp: 'Dr. Sean Brennan',
    referralDate: '02/05/2026',
    diagnosis: 'Pancreatic Adenocarcinoma (suspected)',
    stage: 'Awaiting staging',
    familyHistory: 'Not yet recorded',
    bloods: [
      { test: 'CA19-9', value: 'Not recorded', flag: true },
      { test: 'Bilirubin', value: '42 µmol/L', flag: true },
      { test: 'ALP', value: '180 U/L', flag: true },
      { test: 'Hb', value: '12.1 g/dL', flag: false },
      { test: 'Platelets', value: '260 x10⁹/L', flag: false },
    ],
    reports: [
      { type: 'CT Abdomen/Pelvis', date: '12/05/2026', status: 'Available' },
      { type: 'MRI Pancreas', date: '19/05/2026', status: 'Available' },
      { type: 'Biopsy / Pathology', date: '—', status: 'Not yet uploaded' },
    ],
    timeline: [
      { label: 'Symptoms Onset', date: '20/04/2026', done: true },
      { label: 'GP Referral', date: '02/05/2026', done: true },
      { label: 'Blood Tests', date: '05/05/2026', done: true },
      { label: 'CT Scan', date: '12/05/2026', done: true },
      { label: 'MRI', date: '19/05/2026', done: true },
      { label: 'Biopsy', date: null, done: false },
      { label: 'Diagnosis', date: null, done: false },
      { label: 'MDT Meeting', date: null, done: false },
      { label: 'Treatment', date: null, done: false },
    ],
    mdtNotes: [
      { date: 'Pending', summary: 'No MDT meeting has taken place yet for this patient.' },
    ],
    alerts: [
      { text: 'CA19-9 not recorded', severity: 'high' },
      { text: 'No pathology uploaded', severity: 'high' },
      { text: 'Family history missing', severity: 'medium' },
      { text: 'Awaiting MDT review', severity: 'medium' },
    ],
  }),

  createPatient({
    id: 'p2',
    name: 'John Gallagher',
    dob: '02/11/1971',
    age: 54,
    sex: 'Male',
    mrn: 'MRN-0048213',
    gp: 'Dr. Aoife Quinn',
    referralDate: '10/06/2026',
    diagnosis: 'Pancreatic mass — pending biopsy',
    stage: 'Pre-diagnostic workup',
    familyHistory: 'Father — colorectal cancer, age 70',
    bloods: [
      { test: 'CA19-9', value: '210 U/mL', flag: true },
      { test: 'Bilirubin', value: '18 µmol/L', flag: false },
      { test: 'ALP', value: '95 U/L', flag: false },
      { test: 'Hb', value: '13.4 g/dL', flag: false },
      { test: 'Platelets', value: '310 x10⁹/L', flag: false },
    ],
    reports: [
      { type: 'CT Abdomen/Pelvis', date: '15/06/2026', status: 'Available' },
      { type: 'MRI Pancreas', date: '—', status: 'Not yet uploaded' },
      { type: 'Biopsy / Pathology', date: '—', status: 'Not yet uploaded' },
    ],
    timeline: [
      { label: 'Symptoms Onset', date: '28/05/2026', done: true },
      { label: 'GP Referral', date: '10/06/2026', done: true },
      { label: 'Blood Tests', date: '11/06/2026', done: true },
      { label: 'CT Scan', date: '15/06/2026', done: true },
      { label: 'MRI', date: null, done: false },
      { label: 'Biopsy', date: null, done: false },
      { label: 'Diagnosis', date: null, done: false },
      { label: 'MDT Meeting', date: null, done: false },
      { label: 'Treatment', date: null, done: false },
    ],
    mdtNotes: [
      { date: 'Pending', summary: 'Awaiting MRI before MDT discussion.' },
    ],
    alerts: [
      { text: 'MRI not yet booked', severity: 'high' },
      { text: 'No pathology uploaded', severity: 'high' },
      { text: 'Awaiting MDT review', severity: 'medium' },
    ],
  }),
];