export function createPatient({
  id,
  name,
  dob,
  age,
  sex,
  mrn,
  patient_number,
  gp,
  referralDate,
  diagnosis,
  stage,
  familyHistory,
  bloods,
  reports,
  timeline,
  mdtNotes,
  alerts,
  completeness,
}) {
  return {
    id,
    name,
    dob,
    age,
    sex,

    // raw database value
    patientNumber: patient_number,

    // clinical identifier, as generated by the database trigger
    mrn,

    gp,
    referralDate,
    diagnosis,
    stage,
    familyHistory,
    bloods,
    reports,
    timeline,
    mdtNotes,
    alerts,
    completeness,
  };
}